eureka:
  instance:
    hostname: localhost
    instance-id: localhost:9001
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/

server:
  port: 9001

spring:
  application:
    name: zuul
  zipkin:
    base-url: http://192.168.133.131:9411

zuul:
  routes:
    mysql:
      path: /mysql/*
      serviceId: mysql
    mongo:
      path: /mongo/*
      serviceId: mongo
    redis:
      path: /redis/*
      serviceId: redis