eureka:
  instance:
    hostname: localhost
    instance-id: localhost:9001
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/

server:
  port: 9001

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: server-zuul
  zipkin:
    base-url: http://localhost:9411

zuul:
  routes:
    demo:
      path: /admin/*
      serviceId: server-admin
    mongo:
      path: /mongo/*
      serviceId: server-mongo
    redis:
      path: /redis/*
      serviceId: server-redis