eureka:
  instance:
    hostname: localhost
    instance-id: localhost:9001
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/

server:
  port: 9001

spring:
  application:
    name: server-zuul

zuul:
  routes:
    demo:
      path: /demo/*
      serviceId: server-demo
