eureka:
  instance:
    hostname: localhost
    instance-id: localhost:9003
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/

server:
  port: 9003

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: server-redis

logging:
  config: classpath:log/logback-spring.xml

feign:
  hystrix:
    enabled: true
