eureka:
  instance:
    hostname: localhost
    instance-id: localhost:9002
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/

server:
  port: 9003

spring:
  application:
    name: server-redis
